import {
  CaretDownIcon,
  CaretSortIcon,
  CaretUpIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  Component1Icon,
  DoubleArrowLeftIcon,
  DoubleArrowRightIcon,
  EyeNoneIcon,
  LaptopIcon,
  MixerHorizontalIcon,
  MoonIcon,
  PersonIcon,
  PlusIcon,
  ReloadIcon,
  SunIcon,
  TrashIcon,
} from '@radix-ui/react-icons'

export const Icons = {
  CaretDown: CaretDownIcon,
  CaretSort: CaretSortIcon,
  CaretUp: CaretUpIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  Component1: Component1Icon,
  DoubleArrowLeft: DoubleArrowLeftIcon,
  DoubleArrowRight: DoubleArrowRightIcon,
  EyeNone: EyeNoneIcon,
  Laptop: LaptopIcon,
  MixerHorizontal: MixerHorizontalIcon,
  Moon: MoonIcon,
  Person: PersonIcon,
  Plus: PlusIcon,
  Reload: ReloadIcon,
  Sun: SunIcon,
  Trash: TrashIcon,
}
